spring:
  profiles:
    default: default
  application:
    name: spring
  datasource:
    url: jdbc:h2:mem:spring
    driver-class-name: org.h2.Driver
    username: spring
    password: spring1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jwt:
    secret: /ROHf+Td78MRmPB6SYvxck7HgCSH8ze9lUV7q1UYQYk=
#    secret: ${JWT_SECRET}
    access:
      expiredAt: 300000   # 5분
    email:
      expiredAt: 300000   # 5분